Repository exasol/virtual-schema-common-jdbc, pull requests merged in 2020-01, with the labels that each got.

#17 #16: added tests for adapter notes
  pom.xml
  src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotes.java
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesTest.java
Labels: refactoring

#23 Feature/22 log identifier handling
  pom.xml
  src/main/java/com/exasol/adapter/dialects/AbstractIdentifierConverter.java
  src/main/java/com/exasol/adapter/jdbc/AbstractRemoteMetadataReader.java
Labels: feature

#24 #21: Added warning when tables scan result is empty.
  pom.xml
  src/main/java/com/exasol/adapter/jdbc/AbstractRemoteMetadataReader.java
  src/main/java/com/exasol/adapter/jdbc/BaseTableMetadataReader.java
  src/test/java/com/exasol/adapter/jdbc/AbstractRemoteMetadataReaderTest.java
  src/test/java/com/exasol/adapter/jdbc/BaseTableMetadataReaderTest.java
Labels: enhancement

#25 #20: Refactored ColumnAdapterNotes.
  src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotes.java
  src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverter.java
  src/main/java/com/exasol/adapter/adapternotes/SchemaAdapterNotes.java
  src/main/java/com/exasol/adapter/adapternotes/SchemaAdapterNotesJsonConverter.java
  src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesTest.java
  src/test/java/com/exasol/adapter/adapternotes/SchemaAdapterNotesJsonConverterTest.java
  src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
Labels: refactoring
