Repository exasol/virtual-schema-common-jdbc, pull requests merged in 2020-04, with the labels that each got.

#33 #32: updated dependencies
  pom.xml
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java
  src/test/java/com/exasol/adapter/dialects/BaseQueryRewriterTest.java
  src/test/java/com/exasol/adapter/dialects/SqlDialectRegistryTest.java
  src/test/java/com/exasol/adapter/jdbc/AbstractColumnMetadataReaderTestBase.java
  src/test/java/com/exasol/adapter/jdbc/BaseConnectionDefinitionBuilderTest.java
  src/test/java/com/exasol/adapter/jdbc/BaseRemoteMetadataReaderTest.java
  src/test/java/com/exasol/adapter/jdbc/BaseTableMetadataReaderTest.java
  src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
  src/test/java/com/exasol/adapter/jdbc/JdbcAdapterIT.java
  src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java
  src/test/java/com/exasol/adapter/jdbc/ResultSetMetadataReaderTest.java
  src/test/java/com/exasol/auth/kerberos/KerberosConfigurationCreatorTest.java
Labels: enhancement

#34 Bug/31 add type name to column adapter notes
  launch/vsc-jdbc all test.launch
  pom.xml
  src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotes.java
  src/main/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverter.java
  src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
  src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  src/test/java/com/exasol/ExaConnectionInformationStub.java
  src/test/java/com/exasol/ExaMetadataStub.java
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesJsonConverterTest.java
  src/test/java/com/exasol/adapter/adapternotes/ColumnAdapterNotesTest.java
  src/test/java/com/exasol/adapter/dialects/AbstractQueryRewriterTestBase.java
  src/test/java/com/exasol/adapter/dialects/BaseQueryRewriterTest.java
  src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
Labels: bug

#36 #35: updated to a new vscommon version
  pom.xml
  src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/SqlGenerationVisitorTest.java
  src/test/java/com/exasol/adapter/sql/DummySqlStatement.java
Labels: feature

#40 Bug/139 problem with parentheses
  src/main/java/com/exasol/adapter/dialects/SqlGenerationVisitor.java
  src/test/java/com/exasol/adapter/dialects/SqlGenerationVisitorTest.java
Labels: bug

#42 #41: removed the deleted properties usage
  pom.xml
  src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  src/main/java/com/exasol/adapter/jdbc/BaseConnectionDefinitionBuilder.java
  src/main/java/com/exasol/adapter/jdbc/RemoteConnectionException.java
  src/main/java/com/exasol/adapter/jdbc/RemoteConnectionFactory.java
  src/test/java/com/exasol/adapter/dialects/AbstractSqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/derby/DerbySqlDialect.java
  src/test/java/com/exasol/adapter/dialects/dummy/DummySqlDialect.java
  src/test/java/com/exasol/adapter/dialects/stubdialect/StubSqlDialect.java
  src/test/java/com/exasol/adapter/jdbc/AbstractConnectionDefinitionBuilderTestBase.java
  src/test/java/com/exasol/adapter/jdbc/BaseConnectionDefinitionBuilderTest.java
  src/test/java/com/exasol/adapter/jdbc/JdbcAdapterIT.java
  src/test/java/com/exasol/adapter/jdbc/JdbcAdapterTest.java
  src/test/java/com/exasol/adapter/jdbc/RemoteConnectionFactoryTest.java
Labels: refactoring

#44 Refactoring/43 set mandatory properties
  src/main/java/com/exasol/adapter/dialects/AbstractSqlDialect.java
  src/test/java/com/exasol/adapter/dialects/SqlDialectTest.java
  src/test/java/com/exasol/adapter/dialects/derby/DerbySqlDialect.java
  src/test/java/com/exasol/adapter/dialects/dummy/DummySqlDialect.java
  src/test/java/com/exasol/adapter/dialects/stubdialect/StubSqlDialect.java
Labels: refactoring

#47 #28: improved data types mapping in BaseColumnMetadataReader
  src/main/java/com/exasol/adapter/jdbc/BaseColumnMetadataReader.java
  src/test/java/com/exasol/adapter/jdbc/BaseColumnMetadataReaderTest.java
  src/test/java/com/exasol/adapter/jdbc/ColumnMetadataReaderTest.java
Labels: refactoring
